# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFontComboBox,
    QFrame, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.labelVideo1 = QLabel(self.centralwidget)
        self.labelVideo1.setObjectName(u"labelVideo1")
        self.labelVideo1.setGeometry(QRect(10, 50, 141, 24))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.labelVideo1.setFont(font)
        self.lineEditVideo1 = QLineEdit(self.centralwidget)
        self.lineEditVideo1.setObjectName(u"lineEditVideo1")
        self.lineEditVideo1.setGeometry(QRect(10, 80, 380, 24))
        self.lineEditVideo1.setClearButtonEnabled(False)
        self.pushButtonVideo1Browse = QPushButton(self.centralwidget)
        self.pushButtonVideo1Browse.setObjectName(u"pushButtonVideo1Browse")
        self.pushButtonVideo1Browse.setGeometry(QRect(400, 80, 80, 24))
        self.lineEditVideo2 = QLineEdit(self.centralwidget)
        self.lineEditVideo2.setObjectName(u"lineEditVideo2")
        self.lineEditVideo2.setGeometry(QRect(520, 80, 380, 24))
        self.pushButtonVideo2Browse = QPushButton(self.centralwidget)
        self.pushButtonVideo2Browse.setObjectName(u"pushButtonVideo2Browse")
        self.pushButtonVideo2Browse.setGeometry(QRect(910, 80, 80, 24))
        self.labelVideo2 = QLabel(self.centralwidget)
        self.labelVideo2.setObjectName(u"labelVideo2")
        self.labelVideo2.setGeometry(QRect(520, 50, 151, 24))
        self.labelVideo2.setFont(font)
        self.vline = QFrame(self.centralwidget)
        self.vline.setObjectName(u"vline")
        self.vline.setGeometry(QRect(500, 40, 3, 210))
        self.vline.setFrameShape(QFrame.VLine)
        self.vline.setFrameShadow(QFrame.Sunken)
        self.labelTitle = QLabel(self.centralwidget)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(10, 5, 291, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.labelTitle.setFont(font1)
        self.hlineHeader = QFrame(self.centralwidget)
        self.hlineHeader.setObjectName(u"hlineHeader")
        self.hlineHeader.setGeometry(QRect(0, 40, 1000, 3))
        self.hlineHeader.setFrameShape(QFrame.HLine)
        self.hlineHeader.setFrameShadow(QFrame.Sunken)
        self.hlineContent = QFrame(self.centralwidget)
        self.hlineContent.setObjectName(u"hlineContent")
        self.hlineContent.setGeometry(QRect(0, 250, 1000, 3))
        self.hlineContent.setFrameShape(QFrame.HLine)
        self.hlineContent.setFrameShadow(QFrame.Sunken)
        self.labelStartTimeVideo1 = QLabel(self.centralwidget)
        self.labelStartTimeVideo1.setObjectName(u"labelStartTimeVideo1")
        self.labelStartTimeVideo1.setGeometry(QRect(10, 215, 161, 24))
        font2 = QFont()
        font2.setPointSize(12)
        self.labelStartTimeVideo1.setFont(font2)
        self.lineEditStartTimeVideo1 = QLineEdit(self.centralwidget)
        self.lineEditStartTimeVideo1.setObjectName(u"lineEditStartTimeVideo1")
        self.lineEditStartTimeVideo1.setGeometry(QRect(180, 215, 301, 24))
        self.lineEditStartTimeVideo1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEditDuration = QLineEdit(self.centralwidget)
        self.lineEditDuration.setObjectName(u"lineEditDuration")
        self.lineEditDuration.setGeometry(QRect(10, 310, 180, 24))
        self.lineEditDuration.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelDuration = QLabel(self.centralwidget)
        self.labelDuration.setObjectName(u"labelDuration")
        self.labelDuration.setGeometry(QRect(10, 280, 180, 24))
        self.labelDuration.setFont(font2)
        self.fontComboBoxVideo1 = QFontComboBox(self.centralwidget)
        self.fontComboBoxVideo1.setObjectName(u"fontComboBoxVideo1")
        self.fontComboBoxVideo1.setGeometry(QRect(300, 120, 181, 24))
        self.checkBoxVideo1AddText = QCheckBox(self.centralwidget)
        self.checkBoxVideo1AddText.setObjectName(u"checkBoxVideo1AddText")
        self.checkBoxVideo1AddText.setGeometry(QRect(10, 120, 141, 22))
        self.checkBoxVideo1AddText.setFont(font2)
        self.checkBoxVideo1AddText.setChecked(True)
        self.labelVideo1Font = QLabel(self.centralwidget)
        self.labelVideo1Font.setObjectName(u"labelVideo1Font")
        self.labelVideo1Font.setGeometry(QRect(250, 120, 40, 22))
        self.labelVideo1Font.setFont(font2)
        self.lineEditVideo1Text = QLineEdit(self.centralwidget)
        self.lineEditVideo1Text.setObjectName(u"lineEditVideo1Text")
        self.lineEditVideo1Text.setGeometry(QRect(10, 150, 471, 24))
        self.checkBoxVideo1AddTextBottom = QCheckBox(self.centralwidget)
        self.checkBoxVideo1AddTextBottom.setObjectName(u"checkBoxVideo1AddTextBottom")
        self.checkBoxVideo1AddTextBottom.setGeometry(QRect(110, 180, 80, 22))
        self.checkBoxVideo1AddTextBottom.setFont(font2)
        self.checkBoxVideo1AddTextBottom.setChecked(True)
        self.checkBoxVideo1AddTextTop = QCheckBox(self.centralwidget)
        self.checkBoxVideo1AddTextTop.setObjectName(u"checkBoxVideo1AddTextTop")
        self.checkBoxVideo1AddTextTop.setGeometry(QRect(190, 180, 50, 22))
        self.checkBoxVideo1AddTextTop.setFont(font2)
        self.checkBoxVideo1AddTextMiddle = QCheckBox(self.centralwidget)
        self.checkBoxVideo1AddTextMiddle.setObjectName(u"checkBoxVideo1AddTextMiddle")
        self.checkBoxVideo1AddTextMiddle.setGeometry(QRect(250, 180, 80, 22))
        self.checkBoxVideo1AddTextMiddle.setFont(font2)
        self.labelVideo1TextPosition = QLabel(self.centralwidget)
        self.labelVideo1TextPosition.setObjectName(u"labelVideo1TextPosition")
        self.labelVideo1TextPosition.setGeometry(QRect(10, 180, 90, 24))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setItalic(True)
        self.labelVideo1TextPosition.setFont(font3)
        self.labelVideo2Font = QLabel(self.centralwidget)
        self.labelVideo2Font.setObjectName(u"labelVideo2Font")
        self.labelVideo2Font.setGeometry(QRect(760, 120, 40, 22))
        self.labelVideo2Font.setFont(font2)
        self.checkBoxVideo2AddText = QCheckBox(self.centralwidget)
        self.checkBoxVideo2AddText.setObjectName(u"checkBoxVideo2AddText")
        self.checkBoxVideo2AddText.setGeometry(QRect(520, 120, 141, 22))
        self.checkBoxVideo2AddText.setFont(font2)
        self.checkBoxVideo2AddText.setChecked(True)
        self.checkBoxVideo2AddTextTop = QCheckBox(self.centralwidget)
        self.checkBoxVideo2AddTextTop.setObjectName(u"checkBoxVideo2AddTextTop")
        self.checkBoxVideo2AddTextTop.setGeometry(QRect(690, 180, 80, 22))
        self.checkBoxVideo2AddTextTop.setFont(font2)
        self.fontComboBoxVideo2 = QFontComboBox(self.centralwidget)
        self.fontComboBoxVideo2.setObjectName(u"fontComboBoxVideo2")
        self.fontComboBoxVideo2.setGeometry(QRect(810, 120, 181, 24))
        self.checkBoxVideo2AddTextBottom = QCheckBox(self.centralwidget)
        self.checkBoxVideo2AddTextBottom.setObjectName(u"checkBoxVideo2AddTextBottom")
        self.checkBoxVideo2AddTextBottom.setGeometry(QRect(610, 180, 80, 22))
        self.checkBoxVideo2AddTextBottom.setFont(font2)
        self.checkBoxVideo2AddTextBottom.setChecked(True)
        self.labelVideo2TextPosition = QLabel(self.centralwidget)
        self.labelVideo2TextPosition.setObjectName(u"labelVideo2TextPosition")
        self.labelVideo2TextPosition.setGeometry(QRect(520, 180, 90, 24))
        self.labelVideo2TextPosition.setFont(font3)
        self.lineEditVideo2Text = QLineEdit(self.centralwidget)
        self.lineEditVideo2Text.setObjectName(u"lineEditVideo2Text")
        self.lineEditVideo2Text.setGeometry(QRect(520, 150, 471, 24))
        self.checkBoxVideo2AddTextMiddle = QCheckBox(self.centralwidget)
        self.checkBoxVideo2AddTextMiddle.setObjectName(u"checkBoxVideo2AddTextMiddle")
        self.checkBoxVideo2AddTextMiddle.setGeometry(QRect(750, 180, 80, 22))
        self.checkBoxVideo2AddTextMiddle.setFont(font2)
        self.labelOutput = QLabel(self.centralwidget)
        self.labelOutput.setObjectName(u"labelOutput")
        self.labelOutput.setGeometry(QRect(10, 255, 170, 24))
        self.labelOutput.setFont(font)
        self.lineEditStartTimeVideo2 = QLineEdit(self.centralwidget)
        self.lineEditStartTimeVideo2.setObjectName(u"lineEditStartTimeVideo2")
        self.lineEditStartTimeVideo2.setGeometry(QRect(690, 215, 301, 24))
        self.lineEditStartTimeVideo2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelStartTimeVideo2 = QLabel(self.centralwidget)
        self.labelStartTimeVideo2.setObjectName(u"labelStartTimeVideo2")
        self.labelStartTimeVideo2.setGeometry(QRect(520, 215, 161, 24))
        self.labelStartTimeVideo2.setFont(font2)
        self.labelFPS = QLabel(self.centralwidget)
        self.labelFPS.setObjectName(u"labelFPS")
        self.labelFPS.setGeometry(QRect(210, 280, 180, 24))
        self.labelFPS.setFont(font2)
        self.lineEditFPS = QLineEdit(self.centralwidget)
        self.lineEditFPS.setObjectName(u"lineEditFPS")
        self.lineEditFPS.setGeometry(QRect(210, 310, 180, 24))
        self.lineEditFPS.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelVideoCodec = QLabel(self.centralwidget)
        self.labelVideoCodec.setObjectName(u"labelVideoCodec")
        self.labelVideoCodec.setGeometry(QRect(410, 280, 180, 24))
        self.labelVideoCodec.setFont(font2)
        self.comboBoxVideoCodec = QComboBox(self.centralwidget)
        self.comboBoxVideoCodec.setObjectName(u"comboBoxVideoCodec")
        self.comboBoxVideoCodec.setGeometry(QRect(410, 310, 180, 24))
        self.labelAudioCodec = QLabel(self.centralwidget)
        self.labelAudioCodec.setObjectName(u"labelAudioCodec")
        self.labelAudioCodec.setGeometry(QRect(610, 280, 180, 24))
        self.labelAudioCodec.setFont(font2)
        self.comboBoxAudioCodec = QComboBox(self.centralwidget)
        self.comboBoxAudioCodec.setObjectName(u"comboBoxAudioCodec")
        self.comboBoxAudioCodec.setGeometry(QRect(610, 310, 180, 24))
        self.labelBitrate = QLabel(self.centralwidget)
        self.labelBitrate.setObjectName(u"labelBitrate")
        self.labelBitrate.setGeometry(QRect(810, 280, 180, 24))
        self.labelBitrate.setFont(font2)
        self.lineEditBirate = QLineEdit(self.centralwidget)
        self.lineEditBirate.setObjectName(u"lineEditBirate")
        self.lineEditBirate.setGeometry(QRect(810, 310, 180, 24))
        self.lineEditBirate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.checkBoxOutputVideoDivider = QCheckBox(self.centralwidget)
        self.checkBoxOutputVideoDivider.setObjectName(u"checkBoxOutputVideoDivider")
        self.checkBoxOutputVideoDivider.setGeometry(QRect(10, 345, 171, 22))
        self.checkBoxOutputVideoDivider.setFont(font2)
        self.checkBoxOutputVideoDivider.setChecked(True)
        self.lineEditOutputVideoDividerWidth = QLineEdit(self.centralwidget)
        self.lineEditOutputVideoDividerWidth.setObjectName(u"lineEditOutputVideoDividerWidth")
        self.lineEditOutputVideoDividerWidth.setGeometry(QRect(10, 395, 210, 24))
        self.lineEditOutputVideoDividerWidth.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelOutputVideoDivider = QLabel(self.centralwidget)
        self.labelOutputVideoDivider.setObjectName(u"labelOutputVideoDivider")
        self.labelOutputVideoDivider.setGeometry(QRect(10, 370, 210, 16))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setItalic(True)
        self.labelOutputVideoDivider.setFont(font4)
        self.labelOutputVideoDividerColor = QLabel(self.centralwidget)
        self.labelOutputVideoDividerColor.setObjectName(u"labelOutputVideoDividerColor")
        self.labelOutputVideoDividerColor.setGeometry(QRect(230, 370, 210, 16))
        self.labelOutputVideoDividerColor.setFont(font4)
        self.comboBoxVideoDividerColor = QComboBox(self.centralwidget)
        self.comboBoxVideoDividerColor.addItem("")
        self.comboBoxVideoDividerColor.addItem("")
        self.comboBoxVideoDividerColor.addItem("")
        self.comboBoxVideoDividerColor.setObjectName(u"comboBoxVideoDividerColor")
        self.comboBoxVideoDividerColor.setGeometry(QRect(230, 395, 210, 24))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 480, 980, 30))
        font5 = QFont()
        font5.setPointSize(16)
        self.pushButton.setFont(font5)
        self.comboBoxVideo1AddTextColor = QComboBox(self.centralwidget)
        self.comboBoxVideo1AddTextColor.addItem("")
        self.comboBoxVideo1AddTextColor.addItem("")
        self.comboBoxVideo1AddTextColor.addItem("")
        self.comboBoxVideo1AddTextColor.setObjectName(u"comboBoxVideo1AddTextColor")
        self.comboBoxVideo1AddTextColor.setGeometry(QRect(389, 180, 91, 24))
        self.labelVideo1AddTextColor = QLabel(self.centralwidget)
        self.labelVideo1AddTextColor.setObjectName(u"labelVideo1AddTextColor")
        self.labelVideo1AddTextColor.setGeometry(QRect(345, 180, 40, 24))
        self.labelVideo1AddTextColor.setFont(font3)
        self.comboBoxVideo2AddTextColor = QComboBox(self.centralwidget)
        self.comboBoxVideo2AddTextColor.addItem("")
        self.comboBoxVideo2AddTextColor.addItem("")
        self.comboBoxVideo2AddTextColor.addItem("")
        self.comboBoxVideo2AddTextColor.setObjectName(u"comboBoxVideo2AddTextColor")
        self.comboBoxVideo2AddTextColor.setGeometry(QRect(900, 180, 91, 24))
        self.labelVideo2AddTextColor = QLabel(self.centralwidget)
        self.labelVideo2AddTextColor.setObjectName(u"labelVideo2AddTextColor")
        self.labelVideo2AddTextColor.setGeometry(QRect(855, 180, 40, 24))
        self.labelVideo2AddTextColor.setFont(font3)
        self.checkBoxOutputAudioVideo1 = QCheckBox(self.centralwidget)
        self.checkBoxOutputAudioVideo1.setObjectName(u"checkBoxOutputAudioVideo1")
        self.checkBoxOutputAudioVideo1.setGeometry(QRect(800, 360, 191, 22))
        self.checkBoxOutputAudioVideo1.setFont(font2)
        self.checkBoxOutputAudioVideo1.setChecked(True)
        self.checkBoxOutputAudioVideo2 = QCheckBox(self.centralwidget)
        self.checkBoxOutputAudioVideo2.setObjectName(u"checkBoxOutputAudioVideo2")
        self.checkBoxOutputAudioVideo2.setGeometry(QRect(800, 390, 191, 22))
        self.checkBoxOutputAudioVideo2.setFont(font2)
        self.checkBoxOutputAudioVideo2.setChecked(False)
        self.hlineContent_2 = QFrame(self.centralwidget)
        self.hlineContent_2.setObjectName(u"hlineContent_2")
        self.hlineContent_2.setGeometry(QRect(0, 430, 1000, 3))
        self.hlineContent_2.setFrameShape(QFrame.HLine)
        self.hlineContent_2.setFrameShadow(QFrame.Sunken)
        self.labelOutputVideoFile = QLabel(self.centralwidget)
        self.labelOutputVideoFile.setObjectName(u"labelOutputVideoFile")
        self.labelOutputVideoFile.setGeometry(QRect(10, 440, 141, 24))
        self.labelOutputVideoFile.setFont(font)
        self.lineEditOutputVideoFile = QLineEdit(self.centralwidget)
        self.lineEditOutputVideoFile.setObjectName(u"lineEditOutputVideoFile")
        self.lineEditOutputVideoFile.setGeometry(QRect(160, 440, 501, 24))
        self.lineEditOutputVideoFile.setClearButtonEnabled(False)
        self.pushButtonOutputVideoBrowse = QPushButton(self.centralwidget)
        self.pushButtonOutputVideoBrowse.setObjectName(u"pushButtonOutputVideoBrowse")
        self.pushButtonOutputVideoBrowse.setGeometry(QRect(670, 440, 80, 24))
        self.labelOutputVideoType = QLabel(self.centralwidget)
        self.labelOutputVideoType.setObjectName(u"labelOutputVideoType")
        self.labelOutputVideoType.setGeometry(QRect(780, 440, 81, 24))
        font6 = QFont()
        font6.setPointSize(11)
        self.labelOutputVideoType.setFont(font6)
        self.comboBoxOutputVideoType = QComboBox(self.centralwidget)
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.addItem("")
        self.comboBoxOutputVideoType.setObjectName(u"comboBoxOutputVideoType")
        self.comboBoxOutputVideoType.setGeometry(QRect(870, 440, 121, 24))
        self.plainTextEditOutput = QPlainTextEdit(self.centralwidget)
        self.plainTextEditOutput.setObjectName(u"plainTextEditOutput")
        self.plainTextEditOutput.setGeometry(QRect(10, 520, 980, 250))
        self.logoButton = QPushButton(self.centralwidget)
        self.logoButton.setObjectName(u"logoButton")
        self.logoButton.setGeometry(QRect(830, 0, 168, 40))
        self.logoButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u"images/JMDigital.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logoButton.setIcon(icon)
        self.logoButton.setIconSize(QSize(160, 35))
        self.logoButton.setFlat(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"JMD Video Compare UI", None))
        self.labelVideo1.setText(QCoreApplication.translate("MainWindow", u"Video 1 (left side)", None))
        self.pushButtonVideo1Browse.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.pushButtonVideo2Browse.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.labelVideo2.setText(QCoreApplication.translate("MainWindow", u"Video 2 (right side)", None))
        self.labelTitle.setText(QCoreApplication.translate("MainWindow", u"JMD Video Compare UI", None))
        self.labelStartTimeVideo1.setText(QCoreApplication.translate("MainWindow", u"Start Time (HH:MM:SS)", None))
        self.lineEditStartTimeVideo1.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.lineEditDuration.setText(QCoreApplication.translate("MainWindow", u"00:01:30", None))
        self.labelDuration.setText(QCoreApplication.translate("MainWindow", u"Duration (HH:MM:SS)", None))
        self.checkBoxVideo1AddText.setText(QCoreApplication.translate("MainWindow", u"Add Overlay Text", None))
        self.labelVideo1Font.setText(QCoreApplication.translate("MainWindow", u"Font:", None))
        self.lineEditVideo1Text.setText(QCoreApplication.translate("MainWindow", u"Original", None))
        self.lineEditVideo1Text.setPlaceholderText("")
        self.checkBoxVideo1AddTextBottom.setText(QCoreApplication.translate("MainWindow", u"Bottom", None))
        self.checkBoxVideo1AddTextTop.setText(QCoreApplication.translate("MainWindow", u"Top", None))
        self.checkBoxVideo1AddTextMiddle.setText(QCoreApplication.translate("MainWindow", u"Middle", None))
        self.labelVideo1TextPosition.setText(QCoreApplication.translate("MainWindow", u"Text position:", None))
        self.labelVideo2Font.setText(QCoreApplication.translate("MainWindow", u"Font:", None))
        self.checkBoxVideo2AddText.setText(QCoreApplication.translate("MainWindow", u"Add Overlay Text", None))
        self.checkBoxVideo2AddTextTop.setText(QCoreApplication.translate("MainWindow", u"Top", None))
        self.checkBoxVideo2AddTextBottom.setText(QCoreApplication.translate("MainWindow", u"Bottom", None))
        self.labelVideo2TextPosition.setText(QCoreApplication.translate("MainWindow", u"Text position:", None))
        self.lineEditVideo2Text.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.lineEditVideo2Text.setPlaceholderText("")
        self.checkBoxVideo2AddTextMiddle.setText(QCoreApplication.translate("MainWindow", u"Middle", None))
        self.labelOutput.setText(QCoreApplication.translate("MainWindow", u"Output Video Options", None))
        self.lineEditStartTimeVideo2.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.labelStartTimeVideo2.setText(QCoreApplication.translate("MainWindow", u"Start Time (HH:MM:SS)", None))
        self.labelFPS.setText(QCoreApplication.translate("MainWindow", u"Framerate (FPS)", None))
        self.lineEditFPS.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.labelVideoCodec.setText(QCoreApplication.translate("MainWindow", u"Video Codec", None))
        self.labelAudioCodec.setText(QCoreApplication.translate("MainWindow", u"Audio Codec", None))
        self.labelBitrate.setText(QCoreApplication.translate("MainWindow", u"Bitrate (kbps)", None))
        self.lineEditBirate.setText(QCoreApplication.translate("MainWindow", u"4000", None))
        self.checkBoxOutputVideoDivider.setText(QCoreApplication.translate("MainWindow", u"Add Vertical Divider?", None))
        self.lineEditOutputVideoDividerWidth.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.labelOutputVideoDivider.setText(QCoreApplication.translate("MainWindow", u"Width (in px - must be even number)", None))
        self.labelOutputVideoDividerColor.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.comboBoxVideoDividerColor.setItemText(0, QCoreApplication.translate("MainWindow", u"white", None))
        self.comboBoxVideoDividerColor.setItemText(1, QCoreApplication.translate("MainWindow", u"black", None))
        self.comboBoxVideoDividerColor.setItemText(2, QCoreApplication.translate("MainWindow", u"grey", None))

        self.comboBoxVideoDividerColor.setCurrentText(QCoreApplication.translate("MainWindow", u"white", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Process", None))
        self.comboBoxVideo1AddTextColor.setItemText(0, QCoreApplication.translate("MainWindow", u"white", None))
        self.comboBoxVideo1AddTextColor.setItemText(1, QCoreApplication.translate("MainWindow", u"black", None))
        self.comboBoxVideo1AddTextColor.setItemText(2, QCoreApplication.translate("MainWindow", u"grey", None))

        self.comboBoxVideo1AddTextColor.setCurrentText(QCoreApplication.translate("MainWindow", u"white", None))
        self.labelVideo1AddTextColor.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.comboBoxVideo2AddTextColor.setItemText(0, QCoreApplication.translate("MainWindow", u"white", None))
        self.comboBoxVideo2AddTextColor.setItemText(1, QCoreApplication.translate("MainWindow", u"black", None))
        self.comboBoxVideo2AddTextColor.setItemText(2, QCoreApplication.translate("MainWindow", u"grey", None))

        self.comboBoxVideo2AddTextColor.setCurrentText(QCoreApplication.translate("MainWindow", u"white", None))
        self.labelVideo2AddTextColor.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.checkBoxOutputAudioVideo1.setText(QCoreApplication.translate("MainWindow", u"Use audio from Video 1", None))
        self.checkBoxOutputAudioVideo2.setText(QCoreApplication.translate("MainWindow", u"Use audio from Video 2", None))
        self.labelOutputVideoFile.setText(QCoreApplication.translate("MainWindow", u"Output Video File:", None))
        self.pushButtonOutputVideoBrowse.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.labelOutputVideoType.setText(QCoreApplication.translate("MainWindow", u"Video Type:", None))
        self.comboBoxOutputVideoType.setItemText(0, QCoreApplication.translate("MainWindow", u"mkv", None))
        self.comboBoxOutputVideoType.setItemText(1, QCoreApplication.translate("MainWindow", u"mp4", None))
        self.comboBoxOutputVideoType.setItemText(2, QCoreApplication.translate("MainWindow", u"avi", None))
        self.comboBoxOutputVideoType.setItemText(3, QCoreApplication.translate("MainWindow", u"mov", None))
        self.comboBoxOutputVideoType.setItemText(4, QCoreApplication.translate("MainWindow", u"flv", None))
        self.comboBoxOutputVideoType.setItemText(5, QCoreApplication.translate("MainWindow", u"wmv", None))
        self.comboBoxOutputVideoType.setItemText(6, QCoreApplication.translate("MainWindow", u"webm", None))

        self.logoButton.setText("")
    # retranslateUi

